### ISSUE TITLE
Unhandled Runtime Error

### ISSUE THREAD

**Issue by hoangxuanlam2007** [DariusLukasukas/nextjs-weather-app#2]
Thank you for sharing this repository! I'm a 16-year-old student from Vietnam, and I truly appreciate the effort you've put into this project.

I encountered an error after forking the repository. Here are the steps I followed:

Clone the repository: `npm install && npm run dev`
In my browser, the error displayed as shown in the screenshot: 
![image](https://github.com/DariusLukasukas/nextjs-weather-app/assets/89345805/535145d7-0cdc-4d6c-9a9e-411ca49224f5)
In the terminal, the error was logged as seen in the screenshot: 
![image](https://github.com/DariusLukasukas/nextjs-weather-app/assets/89345805/921bce37-7efc-428d-b0e0-165482ec7de1)

I would appreciate any assistance or guidance on resolving this issue. Thanks again for your hard work!

**Comment by hoangxuanlam2007** [comment]
@DariusLukasukas Hope to see your message soon!

**Comment by DariusLukasukas** [comment]
Thank you for reaching out and for your interest in the project. It's great to see young enthusiasts like you engaging with technology!

I wanted to address the issue you're facing. First, please ensure that you have set up the .env.local file correctly with the necessary environment variables:

VERCEL_URL=localhost:3000
NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=
NEXT_PUBLIC_OPEN_WEATHER_API_KEY=
NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN=

These are essential for the proper functioning of the project.

Additionally, in the actions folder, specifically in all those functions, please check that you're calling the API route using 'http' instead of 'https'. So, it should be http://localhost:3000 and not https://localhost:3000. This is important for local development and testing.

If, after these adjustments, the error still persists, could you provide more detailed information about it? Any error messages, logs, or a clear description of the issue would be very helpful.

Feel free to reply with any further questions or details about the problem. I'm here to help!

**Comment by hoangxuanlam2007** [comment]
> Thank you for reaching out and for your interest in the project. It's great to see young enthusiasts like you engaging with technology!
> 
> I wanted to address the issue you're facing. First, please ensure that you have set up the .env.local file correctly with the necessary environment variables:
> 
> ```
> VERCEL_URL=localhost:3000
> NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=
> NEXT_PUBLIC_OPEN_WEATHER_API_KEY=
> NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN=
> ```
> 
> These are essential for the proper functioning of the project.
> 
> Additionally, in the actions folder, specifically in all those functions, please check that you're calling the API route using 'http' instead of 'https'. So, it should be http://${process.env.VERCEL_URL} and not https://${process.env.VERCEL_URL} This is important for local development and testing.
> 
> If, after these adjustments, the error still persists, could you provide more detailed information about it? Any error messages, logs, or a clear description of the issue would be very helpful.
> 
> Feel free to reply with any further questions or details about the problem. I'm here to help!

Thanks for your assistance, I forgot to mention that I already created the `.env.local` file. After review your comment, I had changed the file contents. I have encountered another error:
![image](https://github.com/DariusLukasukas/nextjs-weather-app/assets/89345805/85d7241a-4829-4e39-9bd0-afcfeda51f4f)

Here is the sidebar (I think the `.env.local` file location is correct): 
![image](https://github.com/DariusLukasukas/nextjs-weather-app/assets/89345805/cf9f5130-9aad-4626-b48e-e02465c0f344)

`getHourlyData.ts`:
![image](https://github.com/DariusLukasukas/nextjs-weather-app/assets/89345805/abe5fa54-4d29-4ef5-890e-c1cf703f5f68)

**Comment by hoangxuanlam2007** [comment]
@DariusLukasukas 
Apologies for the delayed response! I was in class answering your comment using my phone, and our varying time zones made it challenging to communicate promptly. Could we possibly connect through alternative platforms such as Messenger, Discord, Instagram, or any other preferred app of yours? It's perfectly fine too if you don't want. Thank you for your assistance. Your API functionality and the intricacies of their invocation have been truly inspiring me. Additionally, your UI design is impressive!
