### ISSUE TITLE
Wrong ssl number error

### ISSUE THREAD

**Issue by justinajodi** [DariusLukasukas/nextjs-weather-app#8]
⨯ Internal error: TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11372:11) 
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Cause: [Error: A0340000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:355:
] {
  library: 'SSL routines',
  reason: 'wrong version number',
  code: 'ERR_SSL_WRONG_VERSION_NUMBER'
}

![image](https://github.com/DariusLukasukas/nextjs-weather-app/assets/100465157/c98deb02-44a5-43b5-ab0f-16ae9cbc4d29)

**Comment by DariusLukasukas** [comment]
The error you're encountering seems to be related to the URL being used to fetch data in actions. In your local development environment, it's important to use http instead of https. Essentially, when you're working locally, you need to replace https with http in your actions.

Alternatively, you can remove from all actions current endpoint with https and directly modify the env.local file to specify the endpoint URL. You would change:

`VERCEL_URL=localhost:3000`
to:
`VERCEL_URL=http://localhost:3000`

This adjustment ensures that your local development environment communicates correctly with the specified endpoint. Let me know if you need further assistance with this!

**Comment by jeff-hykin** [comment]
I had a similar issue, but the problem was cause it takes 45min for the API key to start working.

Also @DariusLukasukas current fetch calls are ``fetch(`https://${process.env.VERCEL_URL}/`` so I don't think setting the ENV var will work. I had to change them manually
